version: '3.8'

services:
  frontend:
    build:
      context: ./client/servihub-client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3000
      - VITE_WS_URL=ws://backend:3000/ws
      - VITE_JWT_SECRET=your_secret_key
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://root:root@db:5432/db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_secret_key
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: